### ISSUE TITLE
I just need the proper swt.jar for the RPI platform, I am trying to run "janos" on my pi

### ISSUE THREAD

**Issue by kmthinkingrock** [turesheim/eclipse-rpi#2]

**Comment by turesheim** [comment]
I don't know what "Janos" is, but maybe you'll find a usable swt.jar in the zipped repository at https://github.com/turesheim/eclipse-rpi/releases/tag/R1.0

**Comment by turesheim** [comment]
No response. Closing issue.

**Comment by kmthinkingrock** [comment]
Oh, thanks - I was able to find the swt.jar I needed. Thanks for your help
