### ISSUE TITLE
Raspberry Pi4

### ISSUE THREAD

**Issue by natdan** [turesheim/eclipse-rpi#4]
Hi - this is not issue nor complaining for repo not working any more, but being curious if you have any interest trying it again with the latest Raspberry Pi which is getting really close to contemporary definition of 'desktop computer'? I have to admit I did try it and failed (with R4_4, R4_12 and R4_11 versions from eclipse's repos)

**Comment by turesheim** [comment]
Yes, that would be interesting to try out. I just need to get may hand on one of those things first. I have considered ordering one.

**Comment by turesheim** [comment]
So maybe you can help me out a bit. I don't have access to a Raspberry Pi4 quite yet, but I don't think I need one to get this flying. Could you confirm that the architecture is still ARM v6 little endian. Also I suspect the GTK version these days is 3 instead of 2, maybe you could check that.

**Comment by natdan** [comment]
I am not sure about endianness, but architecture comes up as ARMv7 and it is GTK3. Eclipse build scripts have gtk4 as well as gtk3, these days, but I didn't have any luck with gtk4. Gtk3 build worked quite well - minus 32 vs 64bit issues in c/Java code...

**Comment by rikka0w0** [comment]
I'm trying to build Eclipse for aarch64(arm64) but without any success.

**Comment by natdan** [comment]
If you are for quick win - you can pick up what I've done for Raspberry Pi (aarch64): https://blog.abstracthorizon.org/posts/2020/06/eclipse-on-pi4-8gb-64bit-os/

I tried to build it and failed - so reverted onto getting x86_64 version and replaced bits (plugins) with aarch64 versions and put everything manually together...

Alternatively - you can learn from my experience. If you manage to push it further - do let me know.

**Comment by turesheim** [comment]
The Eclipse Foundation now provides an [official build for aarch64](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2020-12/R/eclipse-java-2020-12-R-linux-gtk-aarch64.tar.gz), so I think it's safe to close this one.
